In [ ]:
#Ejercicios 1 de Numpy


In [3]:
import numpy as np
#Ejercicio 1 Crear un vector con valores de 10 a 49
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#Ejercicio 2. Elevar al cuadro a aquellos números divisubles de 3
for i in range(len(a)):
    if a[i]%3==0:
        print(a[i]**2)

144
225
324
441
576
729
900
1089
1296
1521
1764
2025
2304


In [6]:
a[a%3==0]**2

array([ 144,  225,  324,  441,  576,  729,  900, 1089, 1296, 1521, 1764,
       2025, 2304])

In [10]:
#Ejercicio 3 Redimensionar ese vector en una matriz de 20x2
a2 = np.arange(40)
a2.shape
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [11]:
a2.reshape(20,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [ ]:
mat1 = a2.reshape(20, 2)

In [ ]:
#Crear una n ueva matriz de 2x10 y multiplicarla la matriz anterior
mat2

In [12]:
#Obtener la transpueta de la matriz resultante
mat1.transpose()
mat1.T

NameError: name 'mat1' is not defined

In [ ]:
#Ejericio 2
Se desea