
<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Actividad 1: librería NumPy y Pandas.</font>
___




Ahora que hemos hecho el repaso de la líbreria de NumPy, es momento de probar los conocimientos adquiridos. 

<div class="alert alert-danger" style="margin: 10px"><strong>NOTA IMPORTANTE!</strong> Asegúrese de no escribir código en las celdas donde se muestra ejemplificada la salida (etiquetada como "no escribir aquí") <br> de lo contrario, terminará reescribiendo la salida esperada.</div>

#### 1. importar NumPy como np

In [2]:
# CÓDIGO AQUÍ
import numpy as np

#### 2. Crear un arreglo de ceros de tamaño 10 

In [9]:
# CÓDIGO AQUÍ
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
# NO ESCRIBIR AQUÍ

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Crear un arreglo de unos de tamaño 10 

In [15]:
# CÓDIGO AQUÍ
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# NO ESCRIBIR AQUÍ

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Crear un arreglo de cincos de tamaño 10 

In [30]:
# CÓDIGO AQUÍ
np.full(10,5.)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
# NO ESCRIBIR AQUÍ

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Crear un arreglo de enteros que contenga elementos del 10 al 50

In [25]:
# CÓDIGO AQUÍ
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
# NO ESCRIBIR AQUÍ

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Crear un arreglo de todos los enteros pares en el intervalo de 10 a 50

In [26]:
# CÓDIGO AQUÍ
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
# NO ESCRIBIR AQUÍ

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Crear una matriz de 3x3 con valores en el rango de 0 a 8.

In [40]:
# CÓDIGO AQUÍ
m3 = np.arange(0,9)
m3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# NO ESCRIBIR AQUÍ

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Crear una matriz identidad de 3x3

In [32]:
# CÓDIGO AQUÍ
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# NO ESCRIBIR AQUÍ

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Usa NumPy para generar un número aleatorio entre 0 y 1 <br><br>&emsp;NOTA: Tu resultado puede ser diferente al que se muestra en el resultado de ejemplo.

In [36]:
# CÓDIGO AQUÍ
np.random.rand(1)

array([0.11180546])

In [9]:
# NO ESCRIBIR AQUÍ

array([0.65248055])

#### 10. Usa NumPy para generar un arreglo que contenga 25 números aleatorios muestreados a partir de una distribución normal estándar.<br><br>&emsp;&ensp;NOTA: Los valores de su resultado pueden ser diferentes de los que se muestran en el resultado de ejemplo.

In [37]:
# CÓDIGO AQUÍ
np.random.rand(25)

array([0.99043067, 0.03431524, 0.38536772, 0.7577318 , 0.90161988,
       0.29940018, 0.47889002, 0.31037076, 0.55795925, 0.70944064,
       0.50708592, 0.46865475, 0.5512279 , 0.22894911, 0.05223812,
       0.5069879 , 0.32686424, 0.21380397, 0.30194909, 0.03815011,
       0.1519601 , 0.61478539, 0.51390371, 0.03434158, 0.85094932])

In [10]:
# NO ESCRIBIR AQUÍ

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. Crea la matriz que se muestra en la salida de ejemplo:

In [43]:
# CÓDIGO AQUÍ
m10 = np.arange(0.01,1.01,0.01)
m10.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [11]:
# NO ESCRIBIR AQUÍ

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Crea una matriz de tamaño 20 linealmente espaciada en el intervalo de 0 a 1:

In [51]:
# CÓDIGO AQUÍ
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [12]:
# NO ESCRIBIR AQUÍ

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexación y Selección en Numpy 

Ahora se le dará una matriz inicial (¡asegúrese de ejecutar la celda a continuación!) Y se le pedirá que replique las salidas de la matriz que se muestra en la salida de ejemplo:


In [3]:
# EJECUTAR ESTA CELDA. ES NUESTRA MATRIZ DE INICIO
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Escriba código que reproduzca el resultado que se muestra a continuación.<br><br>&emsp;&ensp;Tenga cuidado de no ejecutar la celda inmediatamente arriba de la salida (etiquetada como: "NO ESCRIBIR AQUI"), de lo contrario no podrá ver el resultado de la salida.

In [6]:
# CÓDIGO AQUÍ
mat2 = mat[2:,1:]
mat2

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
# NO ESCRIBIR AQUÍ

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Utilizando el resultado anterior escriba código que reproduzca el resultado que se muestra a continuación.

In [19]:
# CÓDIGO AQUÍ
mat2[1,3]

np.int64(20)

In [ ]:
20

# NO ESCRIBIR AQUÍ

#### 15. Utilizando el resultado de Out[14] Escriba código que reproduzca el resultado que se muestra a continuación.

In [24]:
# CÓDIGO AQUÍ
mat3 = mat2[:,0] -10
mat4 = mat3.reshape(3,1)
mat4

array([[ 2],
       [ 7],
       [12]])

In [16]:
# NO ESCRIBIR AQUÍ

array([[ 2],
       [ 7],
       [12]])

#### 16. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [36]:
# CÓDIGO AQUÍ
mat4 = mat[4:]
mat4

array([[21, 22, 23, 24, 25]])

In [17]:
# NO ESCRIBIR AQUÍ

array([21, 22, 23, 24, 25])

#### 17. Utilizando la matriz contenida en la variable mat, escriba código que reproduzca el resultado que se muestra a continuación.

In [37]:
# CÓDIGO AQUÍ
mat5 = mat[3:]
mat5

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# NO ESCRIBIR AQUÍ

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Operaciones con NumPy

#### 18. Obtenga la suma de todos los valores en mat

In [42]:
# CÓDIGO AQUÍ
mat.sum()

np.int64(325)

In [19]:
# NO ESCRIBIR AQUÍ

325

#### 19. Obtenga la desviación estándar de todos los valores en mat.

In [41]:
# CÓDIGO AQUÍ
mat.std()

np.float64(7.211102550927978)

In [20]:
# NO ESCRIBIR AQUÍ

7.211102550927978

#### 20. Obtenga la suma de todas las columnas en mat

In [44]:
# CÓDIGO AQUÍ
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [21]:
# NO ESCRIBIR AQUÍ

array([55, 60, 65, 70, 75])

## Operaciones con Pandas

**21. importar la librería de pandas**

In [3]:
# código aquí
import pandas as pd

**22. Lea el archivo bank.csv que se encuentra en la carpeta raíz. ¡Presta mucha atención a la ubicación del archivo .csv!.**

In [46]:
# código aquí
pd.read_csv('data/bank.csv')

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

**23. Mustre las primero 5 filas del dataset**

In [5]:
# código aquí
filas_bank = pd.read_csv('data/bank.csv')
filas_bank.head(5)


age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

**24. Calcule el promedio de la edad de las personas del dataset**

In [6]:
# código aquí
df = pd.DataFrame(filas_bank)
df
df['age'].mean()


np.float64(41.17009511170095)

**25. ¿Cuál es el status marital de la persona más joven en el dataset?**



In [66]:
# código aquí
mas_joven = df['age'].min()
jovenes = df[df['age'] == mas_joven]
print("Estatus de las personaa más jovenes")
print(jovenes['marital'])


Estatus de las personaa más jovenes
503     single
1900    single
2780    single
3233    single
Name: marital, dtype: object


**26. ¿Cuántas categorías de trabajos únicos existen en el dataset?**

In [23]:
# código aquí
df['job'].nunique()

12

**27. Muestre cuántas personas hay por categoría de trabajo**

In [25]:
# código aquí
df['job'].value_counts()

job
management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64

**28. ¿Cuál es el porcentaje de las personas en el dataset que están casadas?**

In [27]:
# código aquí
casados = (df['marital']=='married').mean() * 100
print(f"El {casados:.1f}% del Dataset (df) es Casado")

El 61.9% del Dataset (df) es Casado


**29. En el dataset existe una columna etiquetada como: "default". Use el comando .map() para crear una nueva columna llamada "default_code" que contenga el valor 0 si el valor de la columna es "no", o 1 si el valor en la columna esta etiquetada como "si". Muestre los 5 primeros valores de esta nueva columna**


In [75]:
# código aquí
df['default_code'] = df['default'].map({'no': 0, 'yes': 1})
df

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  \
0     cellular   19   oct        79         1     -1         0  unknown  no   
1     cellular   11   may       220         1    339         4  failure  no   
2     cellular   16   apr       185         1    330         1  failure  no   
3      unknown    3   jun       199         4     -1         0  unknown  no   
4      unknown    5   may       226         1     -1         0  unknown  no   
...        ...  ...   ...       ...       ...    ...       ...      ...  ..   
4516  cellular   30   jul       329         5     -1         0  unknown  no   
4517   unknown    9   may       153         1     -1         0  unknown  no   
4518  cellular   19   aug       151        11     -1         0  unknown  no   
4519  cellular    6   feb       129         4    211         3    other  no   
4520  cellular    3   apr       345         2    249         7    other  no   

     marital_code  default_code  
0               m             0  
1               m             0  
2               s             0  
3               m             0  
4               m             0  
...           ...           ...  
4516            m             0  
4517            m             1  
4518            m             0  
4519            m             0  
4520            s             0  

[4521 rows x 19 columns]

**30. Usando el método pandas .apply (), cree una nueva columna llamada "marital_code". Esta columna solo contendrá un código abreviado de la posible primera letra del estado civil. (Por ejemplo, "m" para "casado", "s" para "soltero", etc.**

In [76]:
# código aquí
def codigo_abreviado(x):
    return x[0].lower()

df['marital_code'] = df['marital'].apply(codigo_abreviado)
df

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  \
0     cellular   19   oct        79         1     -1         0  unknown  no   
1     cellular   11   may       220         1    339         4  failure  no   
2     cellular   16   apr       185         1    330         1  failure  no   
3      unknown    3   jun       199         4     -1         0  unknown  no   
4      unknown    5   may       226         1     -1         0  unknown  no   
...        ...  ...   ...       ...       ...    ...       ...      ...  ..   
4516  cellular   30   jul       329         5     -1         0  unknown  no   
4517   unknown    9   may       153         1     -1         0  unknown  no   
4518  cellular   19   aug       151        11     -1         0  unknown  no   
4519  cellular    6   feb       129         4    211         3    other  no   
4520  cellular    3   apr       345         2    249         7    other  no   

     marital_code  default_code  
0               m             0  
1               m             0  
2               s             0  
3               m             0  
4               m             0  
...           ...           ...  
4516            m             0  
4517            m             1  
4518            m             0  
4519            m             0  
4520            s             0  

[4521 rows x 19 columns]

**31. ¿Cuál fue el trabajp con duración más larga?**

In [16]:
# código aquí
df.groupby('job')['duration'].max()

job
admin.           1713
blue-collar      2456
entrepreneur     2769
housemaid        1558
management       2087
retired          1386
self-employed    1877
services         1971
student          1124
technician       2029
unemployed       3025
unknown           789
Name: duration, dtype: int64

**32. ¿Cuál es el nivel de educación más común para las personas que están desempleadas?**

In [94]:
# código aquí
educa = df.loc[df['job'] == 'unemployed', 'education'].value_counts()
educa
educa_max = df.loc[df['job'] == 'unemployed', 'education'].value_counts().idxmax()
print(f"El nivel de educación más común es: {educa_max}")

El nivel de educación más común es: secondary


**33. ¿Cuál es la edad promedio para estar desempleado?**

In [84]:
# código aquí
epd = df.loc[df['job'] == 'unemployed', 'age'].mean()
epd
print(f"La edad promedio para estar desempleado es: {epd:.0f} años")

La edad promedio para estar desempleado es: 41 años
