<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Actividad 4: Programación lineal ( Ejercicios )</font>
___



### 1. Diseño de la Dieta Óptima

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en 100 gramos, se deben tener por lo menos 8 gramos de proteína y 6 gramos de grasa. Así mismo, no se debe tener más de 2 gramos de fibra y 0.4 gramos de sal.  

Los datos nutricionales se pueden obtener de la siguiente tabla:

|Ingrediente|Proteína|Grasa|Fibra|Sal|
|----|---- |---- |---- |---- |
|Pollo|  10.0%|08.0%|00.1%|00.2%
|Carne|  20.0%|10.0%|00.5%|00.5%
|Cordero|15.0%|11.0%|00.5%|00.7%
|Arroz|  00.0%|01.0%|10.0%|00.2%
|Trigo|  04.0%|01.0%|15.0%|00.8%
|Gel|    00.0%|00.0%|00.0%|00.0%

Los costos de cada producto son:

Ingrediente|Costo por gramo
:----|----
Pollo|$\$$0.013
Carne|$\$$0.008
Cordero|$\$$0.010
Arroz|$\$$0.002
Trigo|$\$$0.005
Gel|$\$$0.001    

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, para simplificar la notación se van a nombrar las siguientes variables: 

$x_1:$ Gramos de pollo  
$x_2:$ Gramos de carne  
$x_3:$ Gramos de cordero  
$x_4:$ Gramos de arroz  
$x_5:$ Gramos de trigo  
$x_6:$ Gramos de gel  

Con los datos, se puede plantear la función objetivo, está dada por la siguiente expresión:

$$\min 0.013 x_1 + 0.008 x_2 + 0.010 x_3 + 0.002 x_4 + 0.005 x_5 + 0.001 x_6$$

Las restricciones estarían dadas por el siguiente conjunto de ecuaciones:

$x_1+x_2+x_3+x_4+x_5+x_6=100$  

$(10.0 x_1+ 20.0 x_2+ 15.0 x_3+ 00.0 x_4+ 04.0 x_5+ 00.0 x_6)/100 \geq 8.0$  

$(08.0 x_1+ 10.0 x_2+ 11.0 x_3+ 01.0 x_4+ 01.0 x_5+ 00.0 x_6)/100 \geq 6.0$  

$(00.1 x_1+ 00.5 x_2+ 00.5 x_3+ 10.0 x_4+ 15.0 x_5+ 00.0 x_6)/100 \leq 2.0$  

$(00.2 x_1+ 00.5 x_2+ 00.7 x_3+ 00.2 x_4+ 00.8 x_5+ 00.0 x_6)/100 \leq 0.4$  

La primer condición asegura que la cantidad de productos que se usará cumple con los 100 gramos. Las siguientes sólo siguen los lineamientos planteados para cumplir con los requisitos nutrimentales. 

In [4]:
import numpy as np
from scipy import optimize as opt
#import scipy.optimize as opt

In [43]:
#Creación de la Matrices y cotas

#Valores de la función objetivo, costo por gramo según el ingrediente de x1 a x6
c = np.array([0.013, 0.008, 0.010, 0.002, 0.005, 0.001])

# Restricción la suma de todos los ingredientes es igual a 100
# x1 + x2 + x3 + x4 + x5 + x6 = 100
ingredientes = np.array([[1, 1, 1, 1, 1, 1]])
s_ingredientes = np.array([100])

#Restricciones datos nutricionales 
nutricion = np.array([[-0.10, -0.20, -0.15, 0.0, -0.04, 0.0], #proteina >=8 y <=-8
         [-0.08, -0.10, -0.11, -0.01, -0.01, 0.0],         #grasa >=6 y <=-6
         [0.001, 0.005, 0.005, 0.10, 0.15, 0.0],           #fibra <=2
         [0.002, 0.005, 0.007, 0.002, 0.008, 0.0]])        #sal <=0.4

m_nutricion = np.array([-8, -6, 2, 0.4])

#Cotas
bounds = [(0,None)] * 6


In [44]:
resultado = opt.linprog(c=c, A_ub=nutricion, b_ub=m_nutricion, A_eq=ingredientes, b_eq=s_ingredientes, bounds=bounds,method='highs')
resultado

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 0.52
              x: [ 0.000e+00  6.000e+01  0.000e+00  0.000e+00  0.000e+00
                   4.000e+01]
            nit: 2
          lower:  residual: [ 0.000e+00  6.000e+01  0.000e+00  0.000e+00
                              0.000e+00  4.000e+01]
                 marginals: [ 6.400e-03  0.000e+00  1.300e-03  3.000e-04
                              3.300e-03  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: [ 0.000e+00]
                 marginals: [ 1.000e-03]
        ineqlin:  residual: [ 4.000e+00  0.000e+00  1.700e+00  1.000e-01]
                 marginals: [-0.000e+00 -7.000e-02 -0.000e+00 -0.000e+00]
 mip

In [46]:
c

array([0.013, 0.008, 0.01 , 0.002, 0.005, 0.001])

In [47]:
#Solución Factible, valores óptimos de la mezcla que se debe utilizar en la comida de gato
x_min = resultado.x
np.round(x_min)

array([ 0., 60.,  0.,  0.,  0., 40.])

In [48]:
#Costo mínimo total
c.T.dot(x_min)

np.float64(0.52)

Conclusión:
La mezcla de ingredientes que se debe utilizar para la comida del gato que cumple con todas las restricciones nutricionales son 60 gramos de Carne(x2) y 40 gramos de Gel(x6), por un costo mínimo total de $0.52 (60*0.008)+(40*0.001).

Carne (60 gramos): 12 gramos de proteína >= 8g, 6 gramos de grasa >=6g, 0.3 gramos de fibra <= 2g y 0.3 gramos de sal <= 0.4g.
Gel(40 gramos): me da 0 gramos de proteína, grasa, fibra y sal.

### 2. Otro problema de transporte

Supongamos que tenemos que enviar cajas de cervezas de 2 cervecerías (Modelo y Cuauhtémoc Moctezuma) a 5 bares de acuerdo al siguiente gráfico:

<img style="float: center; margin: 0px 0px 15px 15px;" src="https://relopezbriega.github.io/images/Trans_problem.png" width="500px" height="150px" />

Asimismo, supongamos que nuestro gerente financiero nos informa que el costo de transporte por caja de cada ruta se conforma de acuerdo a la siguiente tabla:

In [27]:
#Crear dataframe
import pandas as pd
info = pd.DataFrame({'Bar1': [2, 3], 'Bar2': [4, 1], 'Bar3': [5, 3], 'Bar4': [2, 2], 'Bar5': [1, 3]}, index = ['CerveceriaA', 'CerveceriaB'])
info

Bar1  Bar2  Bar3  Bar4  Bar5
CerveceriaA     2     4     5     2     1
CerveceriaB     3     1     3     2     3

Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada cervecería (en cajas de cerveza) y cada bar, las cuales se detallan en el gráfico de más arriba.

Sean:
- $x_i$ cajas transportadas de la cervecería A al Bar $i$,
- $x_{i+5}$ cajas transportadas de la cervecería B al Bar $i$.

Plantear el problema de minimizar el costo de transporte de la forma vista y resolverlo con `linprog`. 



In [16]:
import numpy as np
#from scipy.optimize import linprog
from scipy import optimize as opt

In [25]:
# Costos de transporte c = costos
c = np.array([2,4,5,2,1,   # Costo por caja de Cervecería A a cada Bar del 1 al 5
              3,1,3,2,3])   # Costo por caja de Cervecería B a cada Bar del 1 al 5

# Oferta de la Cerveccería A y de la Cervecería B, total de oferta A+B= 5,000
reparto = np.array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])
oferta = np.array([1000, 4000])

# Demanda de cada uno de los cinco Bares, total de demanda b1 + b2 + b3 + b4 + b5= 4,100
captacion = np.array([[1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
                     [0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
                     [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
                     [0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
                     [0, 0, 0, 0, 1, 0, 0, 0, 0, 1]])

demanda = np.array([500, 900, 1800, 200, 700])

#Cotas
bounds = [(0,None)]

In [26]:
resultado = opt.linprog(c=c, A_ub=reparto, b_ub=oferta, A_eq=captacion, b_eq=demanda, bounds=bounds, method='highs')
resultado

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 8600.0
              x: [ 3.000e+02  0.000e+00  0.000e+00  0.000e+00  7.000e+02
                   2.000e+02  9.000e+02  1.800e+03  2.000e+02  0.000e+00]
            nit: 1
          lower:  residual: [ 3.000e+02  0.000e+00  0.000e+00  0.000e+00
                              7.000e+02  2.000e+02  9.000e+02  1.800e+03
                              2.000e+02  0.000e+00]
                 marginals: [ 0.000e+00  4.000e+00  3.000e+00  1.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  1.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                     

In [27]:
c

array([2, 4, 5, 2, 1, 3, 1, 3, 2, 3])

In [31]:
#Entrega de cajas a cada cervecería
x_min = resultado.x
np.round(x_min)

array([ 300.,    0.,    0.,    0.,  700.,  200.,  900., 1800.,  200.,
          0.])

In [32]:
#Costo mínimo total
c.T.dot(x_min)

np.float64(8600.0)

Conclusión:
El costo mínimo total es de $8,600. 
Mapa de entrega de cajas de cervecceria a bar
Cervecería A = (300, 0, 0, 0, 700) = 1,000 cajas repartidas
Cerveceria B = (200, 900, 1800, 200, 0) = 3,100 cajas repartidas
Total entregadas 4,100

Costo = (300*2)+(700*1)+(200*3)+(900*1)+(1800*3)+(200*2)=8,600