<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Tarea 1: Eigenvectores y Eigenvalores</font>
___

Esta tarea consiste en calcular eigenvalores y eigenvectores de matrices siguiendo el calculo a mano, usando la librería numpy y sympy.

Los eigenvalores y eigenvectores son conceptos fundamentales en álgebra lineal y tienen aplicaciones en machine learning, física, ingeniería y más.

In [20]:
import numpy as np
import sympy as sym

**1. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$A = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}$$

In [21]:
# Eigenvalores con numpy
A = np.array([[4,2],[1,3]])
A

array([[4, 2],
       [1, 3]])

In [22]:
x, v = np.linalg.eig(A)
x

array([5., 2.])

In [7]:
#Eigenvectores con numpy
v

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

In [27]:
# Eigenvalores con SymPy
A = sym.Matrix([[4,2],[1,3]])
A

Matrix([
[4, 2],
[1, 3]])

In [28]:
A.eigenvals()

{5: 1, 2: 1}

In [29]:
#Eigenvectores con Sympy
A.eigenvects()

[(2,
  1,
  [Matrix([
   [-1],
   [ 1]])]),
 (5,
  1,
  [Matrix([
   [2],
   [1]])])]

**2. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$B = \begin{bmatrix} 2 & 0 \\ 0 & 5 \end{bmatrix}$$

In [2]:
# Eigenvalores con numpy
B = np.array([[2,0],[0,5]])
B

array([[2, 0],
       [0, 5]])

In [3]:
x, v = np.linalg.eig(B)
x

array([2., 5.])

In [4]:
#Eigenvectores con numpy
v

array([[1., 0.],
       [0., 1.]])

In [24]:
# Eigenvalores con SymPy
B = sym.Matrix([[2,0],[0,5]])
B

Matrix([
[2, 0],
[0, 5]])

In [25]:
B.eigenvals()

{2: 1, 5: 1}

In [26]:
#Eigenvectores con Sympy
B.eigenvects()

[(2,
  1,
  [Matrix([
   [1],
   [0]])]),
 (5,
  1,
  [Matrix([
   [0],
   [1]])])]

**3. Eigenvalores y eigenvectores de una matriz 3x3**

Calcula los eigenvalores y eigenvectores de la siguiente matriz:

$$C = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix}$$

In [5]:
# Eigenvalores con numpy
C = np.array([[1,2,3],[0,4,5],[0,0,6]])
C

array([[1, 2, 3],
       [0, 4, 5],
       [0, 0, 6]])

In [6]:
x, v = np.linalg.eig(C)
x

array([1., 4., 6.])

In [30]:
#Eigenvectores con numpy
v

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

In [31]:
# Eigenvalores con SymPy
C = sym.Matrix([[1,2,3],[0,4,5],[0,0,6]])
C

Matrix([
[1, 2, 3],
[0, 4, 5],
[0, 0, 6]])

In [32]:
C.eigenvals()

{6: 1, 4: 1, 1: 1}

In [33]:
#Eigenvectores con Sympy
C.eigenvects()

[(1,
  1,
  [Matrix([
   [1],
   [0],
   [0]])]),
 (4,
  1,
  [Matrix([
   [2/3],
   [  1],
   [  0]])]),
 (6,
  1,
  [Matrix([
   [8/5],
   [5/2],
   [  1]])])]

**4. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$D = \begin{bmatrix} 0 & 1 \\ -2 & -3 \end{bmatrix}$$

In [9]:
# Eigenvalores con numpy
D = np.array([[0,1],[-2,-3]])
D

array([[ 0,  1],
       [-2, -3]])

In [10]:
x, v = np.linalg.eig(D)
x

array([-1., -2.])

In [37]:
#Eigenvectores con numpy
v

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

In [38]:
# Eigenvalores con SymPy
D = sym.Matrix([[0,1],[-2,-3]])
D

Matrix([
[ 0,  1],
[-2, -3]])

In [41]:
D.eigenvals()

{-1: 1, -2: 1}

In [42]:
#Eigenvectores con Sympy
D.eigenvects()

[(-2,
  1,
  [Matrix([
   [-1/2],
   [   1]])]),
 (-1,
  1,
  [Matrix([
   [-1],
   [ 1]])])]

**5. Crea una matriz cuadrada aleatoria de tamaño 4x4 y calcula sus eigenvalores y eigenvectores.**